<?php
$race = $arrayName = array('high elf' => [
	'str' => 1,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 2,
	'wisdom' => 2,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 2,
	'mind' => 3,
	'lucky' => 1,
	'hp' => 90,
	'mp' => 120,
	'st' => 90],
	'forest elf' => [
	'str' => 2,
	'speed' => 1,
	'dexterity' => 3,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 2,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 2,
	'lucky' => 1,
	'hp' => 100,
	'mp' => 90,
	'st' => 110]);



/*
$race = $arrayName = array('high elf' => [
	'str' => 1,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 1,
	'lucky' => 1,
	'hp' => 1,
	'mp' => 1,
	'st' => 1],
	'forest elf' => [
	'str' => 2,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 1,
	'lucky' => 1,
	'hp' => 1,
	'mp' => 1,
	'st' => 1]
	[
	'str' => 1,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 1,
	'lucky' => 1,
	'hp' => 1,
	'mp' => 1,
	'st' => 1],
	[
	'str' => 1,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 1,
	'lucky' => 1,
	'hp' => 1,
	'mp' => 1,
	'st' => 1],
	[
	'str' => 1,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 1,
	'lucky' => 1,
	'hp' => 1,
	'mp' => 1,
	'st' => 1],
	[
	'str' => 1,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 1,
	'lucky' => 1,
	'hp' => 1,
	'mp' => 1,
	'st' => 1],
	[
	'str' => 1,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 1,
	'lucky' => 1,
	'hp' => 1,
	'mp' => 1,
	'st' => 1],
	[
	'str' => 1,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 1,
	'lucky' => 1,
	'hp' => 1,
	'mp' => 1,
	'st' => 1],
	[
	'str' => 1,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 1,
	'lucky' => 1,
	'hp' => 1,
	'mp' => 1,
	'st' => 1],
	[
	'str' => 1,
	'speed' => 1,
	'dexterity' => 1,
	'stamina' => 1,
	'durability' => 1,
	'reflexes' => 1,
	'accuracy' => 1,
	'intelligence' => 1,
	'wisdom' => 1,
	'intuition' => 1,
	'memory' => 1,
	'charisma' => 1,
	'mind' => 1,
	'lucky' => 1,
	'hp' => 1,
	'mp' => 1,
	'st' => 1],
	);

*/
/*str
speed
dexterity
stamina
durability
reflexes
accuracy
intelligence
wisdom
intuition
memory
charisma
mind
lucky*/
?>

